language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - secure: zHvDuhSFuJKkn6ZOMDd7UzJb2ZG7CL9xBp0Mt2Xzw7ViWGR7qaGbKrEpSsQ/VolU89lcL7UoGuItrnyp15JiZT4lc9QslX/TNwwmbCpGZGbBomeF/I9JzwwSNM7N4xUYRdqOa1IU/9khTILCOBvNyMn3jq+0QvA8JByKUphJx3V0czzU7jwNxgDwYjeu4An5q0KKj16thdGW4URwJdIzZil3NxcVrneNYTiGUHIf6V9gjEtYmg7S31cpm3Sdr8L0WMUnrJRAXpXe4BvTBbRK+7r92b/qBEBmOyjmuDoTS7DhzhxIPftjDHlS6WoGw6FqBfk2YFQaIwtJpXFzmT8dXCxTJGYfYJGq/jf1X55DzYCmfAPGna3614WwHAJAmjP5by4tjxa28w59jI56RGTqZilBIjJyYvOh+oJCstWqD2dTDAEMl5bhjnxh1xlv3PIehi4576g8G9uWHYYjXpYifZHKA9JgXGRK2ME5RqRPDtwlwNyKJLv5ng7tsKIGalFgj6Q9gO/5+AnZ46UdVYsK47SdZ8CxedCu24n1YwtPIdVcaCWBLIXaEAvgC3z9u+DI4Cz28kjdzxNeaejrey2UaFnLYIuzg1xAEn15udvcxA5SE2MDg77XAkIfPla9gpkawk9PUQttoZcHHMiA/TecVDrCDPtdvppmwj5socNtIdc=
  - secure: WvuXxppmHHQ+QUYNt098KmOS9fpHe+TxuHk8elZ+lxRH1W1a4961irYAOXOle0AbzYzz2dtChZ2WO/7c4WAGl5OJ27SccMP2sj8rLXx/9fqwpWNhJeNMQFymBDknPUrdDuznYyQ47/rNPc3L2pmg7PZUelc+4Q9NtMwttjXzAIegq9iYZ7bMhr5f7/bikCHdkuUVigNMQxodtJmVIwPNw/5v2C3EqgdWL6G452L4i8OA4A1mb5E31hXEQlCxMPfBhk5cA4w9V9/q7BO+bSjoluOdHGdizePp9eQohyrT7jMs5N/QNzGcfX/U14Up1SmBKPjm5jB63p4YgSqls994wO6L0lyQ3o3PfMYiTKH2v5cLb4K7YDiY8eXZvlSZurRuh0c8Z0lR4bQJ/ADG1cXx8KEP8dD0FtidpagASKyzTMK0lqNRXmYB0pBz4kRpusPbW7WRiSy6kTBHa4XVD4SmbxyAKQJM1T/mTbFgOfBU8FVaVxHjKpZRnoOJ/lIolkQAv4nv6509J8P0Qfk9rkDKOkhGVrL0z2GkmXzHkLnpAVOQwu3gsoQBuLfmDDR+0rCQAYmUWbuQiuZbMfZq9ciw0EwMAWbn/loyIKl265wlUOs+Um7Hen9HWt5OIqW7Fc2uLBu9LNp5l25tA0FpLRoRleqX7o437TqEre8Sj9pIXXY=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
script:
- yarn test
- yarn run build
after_success:
- test $TRAVIS_BRANCH = "master" && yarn run deploy -- --branch=build
- test $TRAVIS_BRANCH = "prod" && yarn run deploy -- --branch=latest
